sudo: required
language: generic

services: 
  - docker

before_install:
  - docker build -t uygarkaya/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true uygarkaya/react-app npm run test

deploy:
  provider: elasticbeanstalk
  reagion: "us-west-2"
  app: "react-app"
  env: "react-app-env"
  bucket_name: "elasticbeanstalk-us-west-2-XXXXXXXXXXXX"
  bucket_path: "react-app"
  on: 
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY