FROM node:16-alpine

USER node

RUN mkdir -p /home/node/usr/app
WORKDIR /home/node/usr/app

COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./

CMD ["npm", "run", "start"]