version: '3'
services:
  react:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /home/node/usr/app/node_modules
      - .:/home/node/usr/app
  test:
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/usr/app/node_modules
      - .:/home/node/usr/app
    command: ["npm", "run", test]